# Generated by Django 2.2.28 on 2022-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnsLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service01', models.CharField(max_length=10)),
                ('service02', models.CharField(max_length=10)),
                ('service03', models.CharField(max_length=10)),
                ('service04', models.CharField(max_length=10)),
            ],
        ),
    ]
